name: veterinary_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.2.1
  fl_chart: 0.50.1
  permission_handler: ^11.0.1
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: main
  signalr_core: ^1.1.1
  flutter_local_notifications: ^17.0.0
  file_selector: ^1.0.0

  image_picker: ^1.1.2 # Use the latest version
  image_gallery_saver_plus: ^4.0.1 # Use the latest stable version


  flutter_launcher_icons: "^0.13.1"
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon" # Or true, or a custom name like "my_custom_icon"
  ios: true
  image_path: "assets/images/logo_vet_app.png" # Path to your icon image
  min_sdk_android: 23 # Set this to your app's minimum Android SDK version (usually in android/app/build.gradle)
