// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhhI4E09ms5MbzRU9Sd_9-6u41GNzqHU',
    appId: '1:756043924770:web:de04a08799029a8ea7517b',
    messagingSenderId: '756043924770',
    projectId: 'vetappmsgnotification',
    authDomain: 'vetappmsgnotification.firebaseapp.com',
    storageBucket: 'vetappmsgnotification.firebasestorage.app',
    measurementId: 'G-SX6FPWWVWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Pft6oiKVpjixJ9E0LmQM9EGsBE6fOMU',
    appId: '1:756043924770:android:7edac163354d0f80a7517b',
    messagingSenderId: '756043924770',
    projectId: 'vetappmsgnotification',
    storageBucket: 'vetappmsgnotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dOW2xKJvxNUfSes1Fk0V2PVH7f-lLsI',
    appId: '1:756043924770:ios:a4fb51587e0e5076a7517b',
    messagingSenderId: '756043924770',
    projectId: 'vetappmsgnotification',
    storageBucket: 'vetappmsgnotification.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dOW2xKJvxNUfSes1Fk0V2PVH7f-lLsI',
    appId: '1:756043924770:ios:a4fb51587e0e5076a7517b',
    messagingSenderId: '756043924770',
    projectId: 'vetappmsgnotification',
    storageBucket: 'vetappmsgnotification.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGhhI4E09ms5MbzRU9Sd_9-6u41GNzqHU',
    appId: '1:756043924770:web:4a122b473be14d2da7517b',
    messagingSenderId: '756043924770',
    projectId: 'vetappmsgnotification',
    authDomain: 'vetappmsgnotification.firebaseapp.com',
    storageBucket: 'vetappmsgnotification.firebasestorage.app',
    measurementId: 'G-P0C6CFCLWJ',
  );
}
