name: client_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  uni_links: ^0.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff" # Background color of splash
  image: assets/images/splash_app_logo.jpg # Path to your logo image
  android: true
  ios: true
