name: client_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2

  dio: ^5.1.1 # for file download
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.2.1
  url_launcher: ^6.1.7
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.2
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: main
  signalr_core: ^1.1.1
  flutter_local_notifications: ^17.0.0

  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.11"
  file_selector: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_client_app.png

  android_gravity: center
  ios_content_mode: scaleAspectFill

  android: true
  ios: true


flutter_launcher_icons:
  android: "launcher_icon" # Or true, or a custom name like "my_custom_icon"
  ios: true
  image_path: "assets/images/logo_client_app.png" # Path to your icon image
  min_sdk_android: 23 # Set this to your app's minimum Android SDK version (usually in android/app/build.gradle)
